[package]
name = "calculator"
version = "0.1.0"
authors = ["Haska Fikri Tauhid <haskafikritauhid@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.15"
yew = "0.6.0"
meval = "0.2"
regex = "1"